config/routes.rb
Tandem::Application.routes.draw do
  authenticated :user do
    root :to => redirect("/users/tandem")
  end
  
  root :to => "home#index"
  
  resources :appointments
  resources :user_steps

  resources :availables
  resources :coupons

  resources :languages

  resources :interests
  put "rooms/:id/close" => "rooms#close", :as => "close_room"

  put "users/update_language" => "users#update_language", :as => :update_language
  match "users/language" => "users#language", :as => :language_users
  match 'users/tandem' => 'users#tandem', :as => :tandem_users
  match 'users/find' => 'users#find', :as => :find_users
  match 'users/metric' => 'users#metric', :as => :metric_users
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
    controllers: {omniauth_callbacks: "omniauth_callbacks"}

 
  get "home/index"
  get "home/new"

  resources :users

   resources :rooms
   match '/party/:id', :to => "rooms#party", :as => :party, :via => :get
   match '/users/find', :to => "users#find", :as => :find_users, :via => :get

end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :name
  has_many :speak
  has_many :users, :through => :speak
  has_many :improve
  has_many :users, :through => :improve
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  load_and_authorize_resource
  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @languages }
    end
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
    @language = Language.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @language }
    end
  end

  # GET /languages/new
  # GET /languages/new.json
  def new
    @language = Language.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @language }
    end
  end

  # GET /languages/1/edit
  def edit
    @language = Language.find(params[:id])
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(params[:language])

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render json: @language, status: :created, location: @language }
      else
        format.html { render action: "new" }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /languages/1
  # PUT /languages/1.json
  def update
    @language = Language.find(params[:id])

    respond_to do |format|
      if @language.update_attributes(params[:language])
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language = Language.find(params[:id])
    @language.destroy

    respond_to do |format|
      format.html { redirect_to languages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= simple_form_for(@language) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing language</h1>

<%= render 'form' %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<h1>Listing languages</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @languages.each do |language| %>
  <tr>
    <td><%= language.name %></td>
    <td><%= link_to 'Show', language %></td>
    <td><%= link_to 'Edit', edit_language_path(language) %></td>
    <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Language', new_language_path %>

app/views/languages/new.html.erb
<h1>New language</h1>

<%= render 'form' %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @language.name %>
</p>


<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>