config/routes.rb
Tandem::Application.routes.draw do
  authenticated :user do
    root :to => redirect("/users/tandem")
  end
  
  root :to => "home#index"
  
  resources :appointments
  resources :user_steps

  resources :availables
  resources :coupons

  resources :languages

  resources :interests
  put "rooms/:id/close" => "rooms#close", :as => "close_room"

  put "users/update_language" => "users#update_language", :as => :update_language
  match "users/language" => "users#language", :as => :language_users
  match 'users/tandem' => 'users#tandem', :as => :tandem_users
  match 'users/find' => 'users#find', :as => :find_users
  match 'users/metric' => 'users#metric', :as => :metric_users
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
    controllers: {omniauth_callbacks: "omniauth_callbacks"}

 
  get "home/index"
  get "home/new"

  resources :users

   resources :rooms
   match '/party/:id', :to => "rooms#party", :as => :party, :via => :get
   match '/users/find', :to => "users#find", :as => :find_users, :via => :get

end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :setup_default_role_for_new_users, :setup_default_role_for_new_users, :setup_default_subscribed_for_new_users


  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :speak
  has_many :language_speak, :through => :speak, :class_name => "Language"

  has_many :improve
  has_many :language_improve, :through => :improve, :class_name => "Language"
  has_many :hobby
  has_many :interest, :through => :hobby, :class_name => "Interest"




  has_many :appointments 
  has_many :availables



  validates :country, :email, presence: true
  validates :language_speak, :language_improve, presence:true
  ROLES = %w[admin default ambassador banned]
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :language_speak_ids, :language_improve_ids, :country, :interest_ids, :name, :surname, :provider, :role, :sign_in_count, :available_hour_ids, :validated, :code, :subscribed, :foto
  attr_accessor :code
  # attr_accessible :title, :body
  #
 def setup_default_role_for_new_users
    if self.role.blank?
      self.role = "default"
    end
  end

 def setup_default_validated_for_new_users
    if self.validated.nil?
      self.validated = nil
    end
  end
def setup_default_subscribed_for_new_users
    if self.subscribed.nil?
      self.subscribed = nil
    end
end

  def self.from_omniauth(auth, languages)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.first_name
      user.surname = auth.info.last_name
      user.foto = auth.info.image
      user.country = auth.extra.raw_info.locale#Convert contrie from file GB|United Kingdom
  
      if not languages["user"].nil?
        user.language_speak_ids = languages["user"]["language_speak_ids"] 
        user.language_improve_ids = languages["user"]["language_improve_ids"]
      end

    end
   

  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
  else
    super
  end
end
def language?
  if language_improve.empty? or language_speak.empty?
    false
  else
    true
  end
end
#If the user has enough level of their languages they want to improve to be in the platform
def validated?
  return self.validated
end
def subscribed?
  return self.subscribed
end

def compatible?(user)
  if not (user.language_improve & language_speak).empty? and not (user.language_speak & language_improve).empty?
    true
  else
    false
  end
end


def admin?
  if role== "admin"
    true
  else
    false
  end
end
def default?
  if role== "default"
    true
  else
    false
  end
end

def password_required?
  super && provider.blank?
end

def compatible_users
  #users = User.where("orders_count = ? AND locked = ?", language_id, false)#retornar user amb mateix availables i mateixes llengues

end


def update_with_password(params, *options)
  if encrypted_password.blank?
    update_attributes(params, *options)
  else
    super
  end
end

def self.search(search)
  if search
    where(['name LIKE ?', "%#{search}%"])
  else
    scoped
  end
end
def speak_string#TODO
  speak_string = ""
  self.language_speak.each  do |lang|
    if lang != self.language_speak.last 
      speak_string += lang.name + ", "
    else 
      speak_string += lang.name
    end
  end
  speak_string
end

def improve_string#TODO
  improve_string = ""
  self.language_improve.each  do |lang|
    if lang != self.language_improve.last 
      improve_string += lang.name + ", "
    else 
      improve_string += lang.name
    end
  end
  improve_string
end
 
def get_foto
  (self.foto.nil? ||  self.foto.empty?) ? ActionController::Base.helpers.asset_path("icono1.png") :  self.foto
end 

def get_appointments
  Appointment.where("(user_id = ? or user_starter = ?) and (status = ? or status = ?) ", self.id, self.id, 'accepted', 'sent') 
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #For accessing the helper methods in the index view
  helper_method :sort_column, :sort_direction
  # GET /users
  # GET /users.json
  def index
    @users = User.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page =>15, :page => params[:page])#current_user.compatible_users
    authorize! :read, @users

    respond_to do |format|
      #flash[:alert] = "We are under construction. At the moment you can place the time that you are available to speak. The other people will see it and will practice with you :) "
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def metric

    @users = User.all

    @availables = Available.all.size
    @availables_total = @availables.size

    @appointments = Appointment.all.size


    @appointments_sent = Appointment.where("status = ?","sent").size
    @appointments_accepted = Appointment.where("status = ?","accepted").size
    @appointments_canceled = Appointment.where("status = ?","canceled").size
    @tandem_petitions =  @appointments - @appointments_sent - @appointments_accepted - @appointments_canceled



    respond_to do |format|
      #flash[:alert] = "We are under construction. At the moment you can place the time that you are available to speak. The other people will see it and will practice with you :) "
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

   #authorize! :show, @user
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
   authorize! :new, @user
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

   authorize! :create, @user
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
   #authorize! :update, @user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def language

    @user = User.find(current_user.id)
    authorize! :language, :user
    flash[:notice] = "The cockatiel wants to know about your languages."

  end
  def update_language
    @user = User.find(current_user.id)
    authorize! :update_language, :user
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to tandem_users_path, notice: 'You can practice.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def tandem

 
    @available = Available.new
    @user = User.find(current_user.id)
    @appointments = @user.get_appointments
    authorize! :tandem, :user
    @availables = current_user.availables
    
    nuevo = false
    @appointments.each do |appointment|
      
      if ( appointment.status == "sent" && appointment.user_id == current_user.id)
        
        nuevo = true
      end
       



    end
    if nuevo
        
      flash[:alert] = "You have a new tandem request" 
    #       flash[:alert] = render_to_string(:partial => "You have a new tandem request, click  #{link_to('here', appointments_path)}") 

      end
   # authorize! :tandem, @user

  end

  def find
    respond_to do |format|
      format.html { redirect_to users_url, alert: 'We are under construcion. At the moment you can see the other uses avaiable time at'  }
      format.json { head :no_content }
    end
  #appointments = Appointment.find_by_user_id(current_user.id)

  #@all_ids = User.pluck(:id)
  #@selected_page = params[:page] || session[:page] || 0
  #ids = @all_ids.slice( @selected_page * 2 , 2 )
  #@users = User.where(id: ids)
  #@user = User.first
  #authorize! :find, :user
  end
private
#For ordering users in the view index
def sort_column
 User.column_names.include?(params[:sort]) ? params[:sort] : "name"

end

#If the params[direction] is include in [asc,desc] we pass this parameter. Else we pass "asc"
def sort_direction
  %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :surname, :label => "Last Name"  %>
  <%= f.input :foto  %>
  <%= f.input :email, :disabled => true %>
 <%= f.input :country, :label => "Country", :collection =>  [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua And Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegowina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, the Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard and McDonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia, The Former Yugoslav Republic Of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
] %>


  <%= f.input :current_sign_in_at, :disabled => true %>
  <%= f.input :last_sign_in_at , :disabled => true %>
  <%= f.input :current_sign_in_ip , :disabled => true %>
  <%= f.input :last_sign_in_ip , :disabled => true %>
  <%= f.input :provider %>
  <%= f.input :uid , :disabled => true %>

  <%= f.association :language_speak, collection: Language.order(:name) %>
  <%= f.association :language_improve, collection: Language.order(:name) %>

  <%= f.association :interest, collection: Interest.all, as: :check_boxes  %>

  <%= f.input_field :validated, as: :boolean, inline_label: 'Validated?' %>

  <%= f.input_field :subscribed, as: :boolean, inline_label: 'Subscribed?' %>
  <%= f.collection_select :role, User::ROLES, :to_s, :humanize %>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<dl class="dl-horizontal">
<dd> <%=  @user.foto.nil? ?  image_tag("icono1.png") :  image_tag(@user.foto, alt: "Foto #{@user.name} #{@user.surname}")  %></dd>
<dl>
<div class="clear">
</div>
<%= render :partial => 'form' %>

app/views/users/find.erb
<div class="container">


  <div class="row">
    <div class="span4">
      <div class="page-header">
  <h1>Users</h1>
   </div>
 <%= link_to raw("<i class=\"icon-white icon-user\">Search</i>"),
    new_room_path,
    class: "btn btn-success btn-large",
    method: :get %>
  Search form with parameters to be implemented
             <br>
        <br>
        <table class="table table-striped">
          <% @users.each_with_index do |user,i| %>
            <tr>
              <td>
                <img class="img-circle" data-src="holder.js/140x140" alt="140x140" style="width: 140px; height: 140px;" >
              </td>
              <td>
                <img class="img-circle" data-src="holder.js/140x140" alt="140x140" style="width: 140px; height: 140px;" >
              </td>
            </tr>
            <tr>
              <td>Name <%= user.name %></td>
              <td>Name <%= @users[1].name %></td>
              <tr>
              </tr>
              <td>Language/s Improves <%= user.language_improve.name %></td>
              <td>Language/s Improves <%= @users[1].language_improve.name %></td>
            </tr>
            <tr>
              <td>Country <%= user.country %></td>
              <td>Contry <%= @users[1].country %></td>
            </tr>
            <tr>
              <td>Interests <%= user.interest %></td>
              <td>Interests <%= @users[1].interest %></td>
            </tr>
            <tr>
              <td>Puntuation: 3000 pts</td>
              <td>Puntuation: 3000 pts</td>
            </tr>
            <tr>
              <th><%= link_to "View detalis »", {:controller => 'users', :action => 'show', :id => user.id}, :user_id => user.id, :class => "btn" %></th>
              <th><%= link_to "View detalis »", {:controller => 'users', :action => 'show', :id => @users[1].id}, :user_id => user.id, :class => "btn" %></th>
            </tr>

            <% break %>
          <% end %>
        </table>
        <%= link_to raw("<i class=\"icon-white icon-user\">+</i>"),
    new_room_path,
    class: "btn btn-alert btn-large",
    method: :get %>
 <%= link_to raw("<i class=\"icon-white icon-user\">-</i>"),
    new_room_path,
    class: "btn btn-alert btn-large",
    method: :get %>

    </div>
   </div>
</div>

app/views/users/index.html.erb
<% @title="List of tandem partners" %>
<div class="container">
  <div class="row">
<div class="page-header">

<h2 class="featurette-heading">Select <span class="muted">free time</span> of user and make an appointment with him.</h2>



      </div>




<%- model_class = User -%>


</div>
<div class="search">
  <%= form_tag users_path, :method => 'get',:class => 'form-inline' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
    <%= text_field_tag :search, params[:search], placeholder: "Type name of the user ..." %>
    <%= submit_tag "Search", :name => nil, :class => 'btn btn-primary' %>
<% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <% if can? :manage, model_class.model_name %>
        <th><%= sortable "id" %></th>
        <th><%= sortable "email" %></th>
        <th><%= sortable "validated" %></th>
        <th><%= sortable "subscribed" %></th>
        <th><%= sortable "country" %></th>
      <% end %>
      <th><%= sortable "foto" %></th>
      <th><%= sortable "name" %></th>
      <th><%= sortable "surname", "Last Name" %></th>
      <th><%= "Free time"%></th>
      <th><%= model_class.human_attribute_name(:language_speak) %></th>
      <th><%= model_class.human_attribute_name(:language_improve) %></th>
      <% if can? :update, model_class.model_name %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>

      <% if current_user.admin?  %>
        <tr>
          <% if can? :update, model_class.model_name %>
            <td><%= link_to user.id, user_path(user) %></td>
            <td><%= user.email %></td>
      <th><%= user.validated? %></th>
            <td><%= user.subscribed %></td>
            <td><%= user.country %></td>

          <% end %>
          <td><%= link_to user_path(user) do %>
<%= (user.foto.nil? ||  user.foto.empty?) ?  image_tag("icono1.png") :  image_tag(user.foto, alt: "Foto #{user.name} #{user.surname}")  %>
             
             <% end %>
        </td>
          <td><%= user.name %></td>
          <td><%= user.surname %></td>
          <td>
            <small>
                <% user.availables.each do |ava| %>

                       <%= link_to raw("<i class=\"\"> #{ava.day} #{ava.starts.strftime("%H:%M %p")} </i>"),
                         appointments_path(
                                          :appointment =>{:available_id => ava.id}),
                                          class: "btn btn-mini",
                                          :method => :post,
                                          :confirm => "Do you want to send him an email to speak on #{ava.day} at #{ava.starts.strftime("%H:%M %p")}?"
                                        %>
                                    <% end %>

                           </small>
                         </td>
                         <td><% user.language_speak.each do |language|  %>
                           <%= language.name %>
                         <% end %>
                       </td>
                       <td><% user.language_improve.each do |language|  %>
                         <%= language.name %>
                       <% end %>
                     </td>
                     <td>
                       <% if can? :update, model_class.model_name %>
                         <%= link_to raw("<i class=\"icon-white icon-user\">Edit</i>"),
                           {controller: 'users', action: 'edit', id: user.id },
                           class: "btn btn-mini",
                           :method => :get
                         %>
                     <% end %>

                     <% if can? :destroy, model_class.model_name %>
                       <%= link_to raw("<i class=\"icon-white icon-user\">Delete</i>"),
                         {controller: 'users', action: 'destroy', id: user.id },
                         class: "btn btn-mini btn-danger",
                         :method => :delete,
                         data: { confirm: "Are you sure?" }
                       %>

                   <% end %>
                 </td>

               </tr>
             <% elsif current_user.compatible?(user)  %>

               <tr>
                 <% if can? :update, model_class.model_name %>
                   <td><%= link_to user.id, user_path(user) %></td>
                   <td><%= user.email %></td>
                   <td><%= user.country %></td>
                 <% end %>
                 <td>
                  <%= (user.foto.nil? ||  user.foto.empty?) ?  image_tag("icono1.png") :  image_tag(user.foto, alt: "Foto #{user.name} #{user.surname}")  %>
                 </td>
                 <td><%= user.name %></td>
                 <td><%= user.surname %></td>
                 <td>
                   <small>
                     <% user.availables.each do |ava| %>

                       <%= link_to raw("<i class=\"\"> #{ava.day} #{ava.starts.strftime("%H:%M %p")} </i>"),
                         appointments_path(
                                          :appointment =>{:available_id => ava.id}),
                                          class: "btn btn-mini",
                                          :method => :post,
                                          :confirm => "Do you want to send him an email to speak on #{ava.day} at #{ava.starts.strftime("%H:%M %p")}?"
                                        %>
                                    <% end %>
                                  </small>
                                </td>
                                <td><% user.language_speak.each do |language|  %>
                                  <%= language.name %>
                                <% end %>
                              </td>
                              <td><% user.language_improve.each do |language|  %>
                                <%= language.name %>
                              <% end %>
                            </td>
                            <td>
                              <% if can? :update, model_class.model_name %>

                                <%= link_to raw("<i class=\"icon-white icon-user\">Edit</i>"),
                                  {controller: 'users', action: 'edit', id: user.id },
                                  class: "btn btn-mini",
                                  :method => :get
                                %>
                            <% end %>

                            <% if can? :destroy, model_class.model_name %>
                              <%= link_to raw("<i class=\"icon-white icon-user\">Delete</i>"),
                                {controller: 'users', action: 'destroy', id: user.id },
                                class: "btn btn-mini btn-danger",
                                :method => :delete,
                                data: { confirm: "Are you sure?" }
                              %>

                          <% end %>

                        </td>

                      </tr>
                    <% end %>
                  <% end %>

                </tbody>
              </table>
              <%= will_paginate @users %>
<div class="form-actions">

<div class="span6"> </div>
<div class="span7">
 <%= link_to t('.back', :default => t("helpers.links.back")),
              tandem_users_path, :class => 'btn'  %>

   <% if can? :create, model_class.model_name %>
                <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_user_path,
                  :class => 'btn btn-primary' %>

              <% end %>

       </div>

    </div>

 </div>
</div>

app/views/users/language.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Languages</h1>
</div>


<%= simple_form_for @user, :html => { :class => 'form-horizontal' }, :url => update_language_path, :method =>:put  do |f| %>
  <%= f.association :language_speak, collection: Language.order(:name), :label =>"I speak/ I can teach :" %>
  <%= f.association :language_improve, collection: Language.order(:name), :label =>"I am perfectioning/ I learn :"  %>

 <div class="form-actions">
   <%= f.submit "Continue", :class => 'btn btn-primary btn-xlarge'%>
  </div>
<% end %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/personal.html.erb
personal