config/routes.rb
Tandem::Application.routes.draw do
  authenticated :user do
    root :to => redirect("/users/tandem")
  end
  
  root :to => "home#index"
  
  resources :appointments
  resources :user_steps

  resources :availables
  resources :coupons

  resources :languages

  resources :interests
  put "rooms/:id/close" => "rooms#close", :as => "close_room"

  put "users/update_language" => "users#update_language", :as => :update_language
  match "users/language" => "users#language", :as => :language_users
  match 'users/tandem' => 'users#tandem', :as => :tandem_users
  match 'users/find' => 'users#find', :as => :find_users
  match 'users/metric' => 'users#metric', :as => :metric_users
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
    controllers: {omniauth_callbacks: "omniauth_callbacks"}

 
  get "home/index"
  get "home/new"

  resources :users

   resources :rooms
   match '/party/:id', :to => "rooms#party", :as => :party, :via => :get
   match '/users/find', :to => "users#find", :as => :find_users, :via => :get

end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :publisher_id , :available , :session_id , :asset
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :config_opentok,:except => [:index]
  def index
    authorize! :update, @room
    @rooms = Room.page(params[:page]).per_page(15)
    @all_rooms = Room.all
    @iniciated_rooms = 0
    @all_rooms.map{|room| @iniciated_rooms+=1 if  room.available}
  end
  def new
    #Customer information

       
    room_found = false
    @rooms = Room.where(:available =>true).order('created_at ASC')

    if not @rooms.empty?#to find if there is rooms waiting for a user to join
      @rooms.each do |room|
        
        user = User.find(room.publisher_id)#has to be adapted to de ID
        if not (user.language_improve & current_user.language_speak).empty? and not (user.language_speak & current_user.language_improve).empty? #To make the user with same demanding languages and ofering languages go to the same room
          room.update_attributes(:available => false ) #It can't be accesed again
          room.save!
          $customerio.track(current_user.id, "party_view",:type => "joined", :number => room.id.to_s)
          redirect_to("/party/"+room.id.to_s)

          room_found = true
          break
        end
      end
    end
    if @rooms.empty? or not room_found # when there is not rooms or if there is not appropiate rooms
      #p2p conexion#session_properties = {OpenTok::SessionPropertyConstants::P2P_PREFERENCE => "enabled"}
      #session = @opentok.create_session request.remote_addr, session_properties

      session = @opentok.create_session request.remote_addr
      @new_room = Room.new(:publisher_id => current_user.id.to_s, :available => true,:session_id => session.session_id)

      respond_to do |format|
        if @new_room.save
          $customerio.track(current_user.id, "party_view",:type => "created")
          format.html { redirect_to("/party/"+@new_room.id.to_s) }
        else
          format.html { render :controller => 'user',
            :action => "tandem" }
          end
        end
      end

    end
  def party
    @room = Room.find(params[:id])
    @tok_token = @opentok.generate_token :session_id =>@room.session_id, :expire_time => Time.now.to_i + 60*60

  end


  def show
    id = params[:id]
    @room = Room.find(id)
    render :partial => 'room', :locals => {:room => @room} and
      return if request.xhr?
  end

  def close
    @room = Room.find(params[:id])
    authorize! :close, :room
    if @room.update_attribute(:available, false)
      render("/users/tandem")
    else
      redirect :controller => 'rooms', :action => "tandem"
    end
  end

  private
  def config_opentok

    if @opentok.nil?
      @opentok = OpenTok::OpenTokSDK.new "7638152", "d1de3d0a7229cc4e46e9a83a1b35f4d14ad6f56b"
    end
  end


  end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for @room, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :id %>
  <%= f.input :publisher_id  %>
<% end %>

app/views/rooms/_room.html.erb
<p><%= User.find(@room.publisher_id).name %>, somebody is going to conect soon. Please wait :)</p>
<p>This room is available: <%= @room.available %></p>

app/views/rooms/config_opentok.html.erb
<h1>Rooms#config_opentok</h1>
<p>Find me in app/views/rooms/config_opentok.html.erb</p>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/index.html.erb
<div class="container">
  <div class="row">
<div class="page-header">

<h2 class="featurette-heading">Rooms <span class="muted">list</span></h2>
      </div>
<div class="well well-large">
  Number of rooms created: <%= @all_rooms.size %>
  Number of rooms iniciated: <%= @iniciated_rooms %> 


</div>
 

  <%= will_paginate @rooms %>

    <div class="span7">



            <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>Id</th>
            <th>Created</th>
            <th>Available</th>
            <th>Joined at</th>
            <th>Duration</th>
            <th>publisher id</th>
            <th>subscriber id</th>
          </tr>
        </thead>
        <% @rooms.each do |room| %>

            <tr>
              <td><%= room.id %></td>
              <td><%= room.created_at.strftime("%m-%d %H:%M")%></td>
              <td><%= room.available %></td>
              <td><%= room.joined_at.strftime("%H:%M") unless room.joined_at.nil?  %></td>
              <td><%= room.duration.strftime("%H:%M")  unless room.duration.nil?  %></td>
              <td><%=room.publisher_id  %></td>
              <td><%=  room.subscriber_id  %></td>

        </tr>
      <% end %>
  </table>
       </div>

</div>

<div class="clear">

 <%= link_to t('.back', :default => t("helpers.links.back")),
              tandem_users_path, :class => 'btn pull-left '  %>


</div>

app/views/rooms/party.html.erb
<% @title="Videoconference screen" %>
<div class="container">
  <div class="row">
    <div class="span1">
    </div>
    <div class="span7">
<h3> Speak now, don't be afraid </h3>
          <div id="videobox"></div>
          <div id='wrapper'>
            <div id='subscriber'>There is no one online. Click on <%= link_to raw("<i class=\"icon-user\"></i> ") + "List of users", users_path %> to ask for a tandem! </div>
            <div id='publisher'></div>
          </div>
          <style type="text/css">
            body {
            text-align: center;
            }

            #wrapper {
            margin: 0 auto;
            position: relative;
            width: 640px;
            height: 480px;
            }

            #subscriber {
            position: relative;
            width: 100%;
            height: 100%;
            z-index: 1;

            }

            #publisher {
            position: absolute;
            width: 160px;
            height: 120px;
            z-index: 10;
            bottom: 10px;
            left: 10px;
            }

            #publisher_div {
            border: 1px solid white;
            }

            #subscriber_div, #publisher_div {
            width: 100%; height: 100%;
            }

          </style>

          <script src='https://swww.tokbox.com/webrtc/v2.0/js/TB.min.js'></script>
          <script language="JavaScript" type="text/javascript">

var apiKey = "7638152";
  var session_id = "<%= @room.session_id %>";
  var token ="<%= @tok_token %>";
    var session;
    var publisher;
    $(document).ready(function() {
        TB.setLogLevel(5);
        session = TB.initSession(session_id);
        session.addEventListener("sessionConnected", sessionConnectedHandler);
        session.addEventListener("streamCreated", streamCreatedHandler);
        session.connect(apiKey, token);
        });


// Our countdown plugin takes a callback, a duration, and an optional message
$.fn.countdown = function (callback, duration, message) {
    // If no message is provided, we use an empty string
    message = message || "";
    // Get reference to container, and set initial content
    var container = $(this[0]).html(duration + message);
    // Get reference to the interval doing the countdown
    var countdown = setInterval(function () {
        // If seconds remain
        if (--duration) {
            // Update our container's message
            container.html(duration + message);
        // Otherwise
        } else {
            // Clear the countdown interval
            clearInterval(countdown);
            // And fire the callback passing our container as `this`
            callback.call(container);
        }
    // Run interval every 1000ms (1 second)
    }, 1000);

};

// Function to be called after 5 seconds
function redirect () {
  this.html("<h1>The tandem has finished. </h1>");
     $.ajax({
url: '../rooms/<%= Room.find(params[:id]).id %>/close',
async: false,
type: "PUT"
});
  //window.location = "http://localhost:3000/users/tandem";
window.location = "<%= tandem_users_path %>";
  //alert("The tandem has ended. Please send us some feedback")
 }




function sessionConnectedHandler(event) {
  $("#publisher").append("<div id='publisher_div'></div>");
  publisher = TB.initPublisher(apiKey, "publisher_div");
  publisher.addEventListener('accessAllowed', accessAllowedHandler);
  streamCreatedHandler(event);

}

function accessAllowedHandler(event) {
  $("#publisher_div").css("width", "100%").css("height", "100%");
  session.publish(publisher);
}

function streamCreatedHandler(event) {
   var stream = event.streams[0];
  if (stream.connection.connectionId != session.connection.connectionId) {
    $("#subscriber").append("<div id='subscriber_div'></div>");
    session.subscribe(event.streams[0], "subscriber_div");
    $("#subscriber_div").css("width", "100%").css("height", "100%");

     // Use p.countdown as container, pass redirect, duration, and optional message
    $(".countdown").countdown(redirect, 3600 , "s aproximate time to finish");

  }



}






























  window.onbeforeunload = function(e) {
    //We close the room when the user exits the window
    $.ajax({
url: '../rooms/<%= Room.find(params[:id]).id %>/close',
async: false,
type: "PUT"
});
}


</script>
 <div class="clear">
  <div id="information">
  <p><%= link_to "Update information" , room_path, :id => 'link' %></p>
</div>
  <h2>Trophies and Badges</h2>
  <%= image_tag "premios-01.png" %>x 0  <%= image_tag "premios-02.png" %>x 0
  <%= image_tag "premios-06.png" %>x 0
  <%= image_tag "premios-05.png" %>x 1

</div>

  </div>
  <div class="span4">
    <br>
    <br>
    <br>
    <%=  image_tag "recomendaciones.png" %>
<p class="countdown"></p>
    <%  @room = Room.find(params[:id]) %>
    <div class="clear">
    </div>


    <br>
    <br>
    <br>
    <br> <%  @room = Room.find(params[:id]) %>
     <%= link_to raw("<i class=\"icon-white icon-off\"> Close</i>"),
          close_room_path(@room),
          class: "btn btn-info btn-large",
          method: :put,
          rel:'popover',
         data: {placement: 'left',  toggle: 'popover', trigger: 'hover', content: 'Set your schedule and program a regular tandem with an awesome partner' }
        %>
  </div>
</div>
</div>