config/routes.rb
Tandem::Application.routes.draw do
  authenticated :user do
    root :to => redirect("/users/tandem")
  end
  
  root :to => "home#index"
  
  resources :appointments
  resources :user_steps

  resources :availables
  resources :coupons

  resources :languages

  resources :interests
  put "rooms/:id/close" => "rooms#close", :as => "close_room"

  put "users/update_language" => "users#update_language", :as => :update_language
  match "users/language" => "users#language", :as => :language_users
  match 'users/tandem' => 'users#tandem', :as => :tandem_users
  match 'users/find' => 'users#find', :as => :find_users
  match 'users/metric' => 'users#metric', :as => :metric_users
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
    controllers: {omniauth_callbacks: "omniauth_callbacks"}

 
  get "home/index"
  get "home/new"

  resources :users

   resources :rooms
   match '/party/:id', :to => "rooms#party", :as => :party, :via => :get
   match '/users/find', :to => "users#find", :as => :find_users, :via => :get

end

app/models/available.rb
class Available < ActiveRecord::Base
  attr_accessible :day, :duration, :starts, :user_id

  has_many :appointments, dependent: :destroy
  belongs_to :user

  DAYS = %w[Monday Tuesday Wednesday Thursday Friday Saturday Sunday]
  def start_end_time
    '' +self.starts.strftime("%I:%M%p") + '-' + ((self.starts + self.duration)).strftime("%I:%M%p")+''

  end

end

app/controllers/availables_controller.rb
class AvailablesController < ApplicationController
  # GET /availables
  # GET /availables.json
  def index
    @available = Available.new
    @availables = current_user.availables

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @availables }
    end
  end

  # GET /availables/1
  # GET /availables/1.json
  def show
    @available = Available.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @available }
    end
  end

  # GET /availables/new
  # GET /availables/new.json
  def new
    @available = Available.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @available }
    end
  end

  # GET /availables/1/edit
  def edit
    @available = Available.find(params[:id])
  end

  # POST /availables
  # POST /availables.json
  def create
   $customerio.track(current_user.id, "availables",:type => "created")
   days = params[:available][:day].reject! { |c| c.empty? }
   days.empty? ? all_record_saved = false : all_record_saved = true
   days.each do |day|
     available = Available.new("day"=>day, "starts"=>params[:available][:starts])
     if available.save!
      current_user.availables << available
     else
      all_record_saved = false
     end
  end
  respond_to do |format|
    if all_record_saved
      format.html { redirect_to :back }
    else
      format.html { redirect_to :back, alert: 'Maybe some hours have not been added, check them out' }
    end
  end

end



  # PUT /availables/1
  # PUT /availables/1.json
  def update
    $customerio.track(current_user.id, "availables",:type => "updated")

    @available = Available.find(params[:id])

    respond_to do |format|
      if @available.update_attributes(params[:available])
        format.html { redirect_to @available, notice: 'Available was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @available.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availables/1
  # DELETE /availables/1.json
  def destroy
    @available = Available.find(params[:id])
    @available.destroy

    respond_to do |format|
      format.html { redirect_to availables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/availables_helper.rb
module AvailablesHelper
end

app/views/availables/_form.html.erb
<%= simple_form_for(@available) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :day %>
    <%= f.input :starts %>
    <%= f.input :duration %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/availables/edit.html.erb
<% @title="Edit available time to tandem" %>
<h1>Editing available</h1>

<%= render 'form' %>

<%= link_to 'Show', @available %> |
<%= link_to 'Back', availables_path %>

app/views/availables/index.html.erb
<% @title="Free time to tandem" %>
<div class="container">
  <div class="row">
<div class="page-header">

<h2 class="featurette-heading">What <span class="muted">time</span> are you available to tandem?</h2>
      </div>


      <div class="span5">

 <%= simple_form_for(@available) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">

      <%= f.label "Day of the week" %>
      <%= f.collection_select :day, Available::DAYS, :to_s, :humanize,:label => "Day of week"  %>


      <%= f.label :starts," At what hour(GMT+1) are you available?" %>

      <%= f.time_select :starts, :default =>Time.now.beginning_of_hour,:minute_step => 15 %>

      <%= f.input :duration, :label =>"Duration of the tandem", :default => Time.now.beginning_of_day, :minute_step => 15,:prompt => {:hour => 'Choose hours duration', :minute => 'Choose minutes of duration'} %>


    </div>
      <%= f.button :submit,"Add free time",:class =>"btn btn-primary btn-large" %>
  <% end %>





       </div>


    <div class="span7">

<h3 class="featurette-heading">List of <span class="muted">hours</span> I am available</h3>


            <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>Day</th>
            <th>Hour (GMT+1)</th>
          </tr>
        </thead>
        <% @availables.each do |ava| %>

            <tr>
              <td><%= ava.day %></td>
              <td><%= ava.starts.strftime("%H:%M") %></td>
              <td>
                <%= link_to raw("<i class=\"icon-white icon-calendar\">Edit</i>"),
                  {controller: 'availables', action: 'edit' , id: ava.id},
                  class: "btn btn-mini",
                  :method => :get
                %>

              <%= link_to raw("<i class=\"icon-white icon-calendar\">Delete</i>"),
                {controller: 'availables', action: 'destroy' , id: ava.id},
                class: "btn btn-mini btn-danger",
                :method => :delete,
                data: { confirm: "Are you sure?" }
              %>
          </td>

        </tr>
      <% end %>
  
  </table>
       </div>

</div>

<div class="clear">
</div>

    <div class="form-actions">

<div class="span1"> </div>
<div class="span7">

 <%= link_to t('.back', :default => t("helpers.links.back")),
              tandem_users_path, :class => 'btn pull-left '  %>

      <%= link_to raw("<i class=\"icon-white \">Continue</i>"),
    {controller: 'users', action: 'index'},
    class: "btn btn-primary pull-right",
  rel:'popover',
         data: {placement: 'right',  toggle: 'popover', trigger: 'hover', content: 'Awesome native speakers are wating for you. Go catch your exchange partner' }
    %>

      </div>

    </div>
  <br />
  <br />
  <br />

    <div class="span5">
    </div>
    <div class="span1">
       </div>
    <div class="span5">
    </div>



</div>

app/views/availables/new.html.erb
<h1>New available</h1>

<%= render 'form' %>

<%= link_to 'Back', availables_path %>

app/views/availables/show.html.erb
<% @title="Show available" %>
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @available.day %>
</p>

<p>
  <b>Starts:</b>
  <%= @available.starts %>
</p>

<p>
  <b>Duration:</b>
  <%= @available.duration %>
</p>


<%= link_to 'Edit', edit_available_path(@available) %> |
<%= link_to 'Back', availables_path %>